homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elev
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  customize: !include custimize.yaml

# Enables the frontend
frontend:
# Enables configuration UI
config:
# Zones
zone: !include_dir_list zones/
# MQTT
mqtt: !include mqtt.yaml
# Http
http: !include http.yaml
# Media Players and TV's
media_player: !include media_devices.yaml
# Device Trackers
device_tracker: !include device_trackers.yaml
# Scenes
scene: !include scenes.yaml
# Sensors
sensor: !include sensors.yaml
# Binary Sensors
binary_sensor: !include binary_sensors.yaml
# Input Boolean Components
input_boolean: !include input_booleans.yaml
# Input Sliders
input_slider: !include input_sliders.yaml
# Input Select
#input_select: !include input_selectors.yaml
# Lights
light: !include lights.yaml
# Scripts
script: !include scripts.yaml
# Switches
switch: !include switches.yaml

notify: !include notify.yaml

# Emulated Hue to find Sony TV
emulated_hue:
  host_ip: !secret ha_ip
  listen_port: 8300
  expose_by_default: true
  exposed_domains:
    - media_player

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
#updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically - Ignoring Google Cast as TV will be shown twice
#discovery:
#  ignore:
#    - google_cast

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:
recorder:
  purge_days: 5
  exclude:
    domains:
      - automation
      - group
      - script
      - scene
      - input_slider
      - sensor
      - zone
      - light
    entities:
      - sun.sun   # Don't record sun data
  include:
    entities:
      - light.bedroom
      - light.entrance
      - light.stairs
      - light.lamp
      - sensor.cpu_temperature
      - sensor.cpu_use
      - sensor.ram_use
      - sensor.hall_light_level
      - sensor.hall_temperature
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.speedtest_ping
      - sensor.hall_motion_sensor_last_update


# View all events in a logbook
#logbook:

# Track the sun
sun:

# Set Logger to see issues
logger:
  default: warning
  logs:
    aiohttp.access: critical

# Text to speech
tts:
  - platform: google

group: !include groups.yaml
automation: !include automations.yaml
